language: minimal
dist: xenial
group: travis_latest

os: linux

git:
  depth: 25
  quiet: true
  submodules: true

env: FC=gfortran CPPFLAGS="" NETCDFINC=-I/usr/include NETCDFLIB="-L/usr/lib/x86_64-linux-gnu/ -lnetcdff -lnetcdf"

addons:
  apt:
    packages:
    - gfortran
    - libnetcdf-dev
    - libnetcdff-dev

install:
- make umwm
    
script:
- ./umwm
